name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # O el nombre de la rama que prefieras

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker://jekyll/jekyll:latest

      - name: Build the Jekyll site
        run: docker run --rm -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site jekyll/jekyll jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

